version: "3"
services:
  redis:
    image: docker.io/redis
    container_name: qrcode-redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    networks:
      - oauth-test
  mysql:
    image: mysql:5.7.19
    container_name: qrcode-mysql
    hostname: mysql
    volumes:
      - "./docker/data/mysql:/var/lib/mysql"
      - "./docker/conf/mysql:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    networks:
      - oauth-test
networks:
  oauth-test: